# Generated by Django 5.0.2 on 2024-03-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetworking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='type',
            field=models.CharField(default='Follow', max_length=15),
        ),
        migrations.AlterField(
            model_name='like',
            name='type',
            field=models.CharField(default='Like', max_length=15),
        ),
    ]
