# Generated by Django 5.0.2 on 2024-02-21 19:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetworking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.URLField()),
                ('origin', models.URLField()),
                ('description', models.CharField(max_length=300)),
                ('contentType', models.CharField(choices=[('COMMON_MARK', 'text/markdown'), ('PLAIN', 'text/plain'), ('BASE64', 'application/base64'), ('PNG', 'image/png;base64'), ('JPEG', 'image/jpeg;base64')], default='PLAIN', max_length=30)),
                ('content', models.BinaryField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('FRIENDS', 'Friends')], default='PUBLIC', max_length=10)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('author_of_posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_set', to='socialNetworking.author')),
            ],
        ),
    ]
