# Generated by Django 5.0.2 on 2024-03-18 00:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetworking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialNetworking.author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialNetworking.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 0, 49, 25, 591033, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='follow',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_follow_set', to='socialNetworking.author'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='object_of_follow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_of_follow_set', to='socialNetworking.author'),
        ),
        migrations.AlterField(
            model_name='like',
            name='author_like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='socialNetworking.author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_of_posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_set', to='socialNetworking.author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/markdown', 'text/markdown'), ('text/plain', 'text/plain'), ('application/base64', 'application/base64'), ('image/png;base64', 'image/png;base64'), ('image/jpeg;base64', 'image/jpeg;base64')], default='PLAIN', max_length=30),
        ),
    ]
