# Generated by Django 5.0.2 on 2024-03-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetworking', '0002_post_num_likes_alter_like_author_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='num_likes',
            field=models.IntegerField(default=0),
        ),
    ]
