# Generated by Django 5.0.2 on 2024-02-17 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetworking', '0002_rename_author_authors_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_follow_set', to='socialNetworking.authors')),
                ('object_of_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_of_follow_set', to='socialNetworking.authors')),
            ],
        ),
    ]
