# Generated by Django 5.0.2 on 2024-04-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetworking', '0002_alter_follow_type_alter_like_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_approval', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'User Approval',
            },
        ),
    ]
