# Generated by Django 5.0.2 on 2024-03-19 00:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetworking', '0003_author_draftdisplayname_author_draftgithub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('host_url', models.URLField(primary_key=True, serialize=False)),
                ('api_url', models.URLField()),
                ('username_in', models.CharField(max_length=20)),
                ('password_in', models.CharField(max_length=20)),
                ('username_out', models.CharField(max_length=20)),
                ('password_out', models.CharField(max_length=20)),
                ('approved', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/markdown', 'text/markdown'), ('text/plain', 'text/plain'), ('application/base64', 'application/base64'), ('image/png;base64', 'image/png;base64'), ('image/jpeg;base64', 'image/jpeg;base64')], default='text/plain', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
