# Generated by Django 5.0.2 on 2024-03-12 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetworking', '0003_comment_num_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='socialNetworking.post'),
        ),
    ]
