# Generated by Django 5.0.2 on 2024-02-21 20:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetworking', '0003_alter_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('contentType', models.CharField(default='text/markdown', editable=False, max_length=20)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialNetworking.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialNetworking.post')),
            ],
        ),
    ]
