# Generated by Django 5.0.2 on 2024-03-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetworking', '0004_alter_like_like_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='context',
        ),
        migrations.AddField(
            model_name='comment',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='object',
            field=models.URLField(null=True),
        ),
    ]
