# Generated by Django 5.0.2 on 2024-03-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetworking', '0004_alter_post_contenttype_alter_post_published_at_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
