# Generated by Django 5.0.2 on 2024-02-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetworking', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(default='comment', editable=False, max_length=15),
        ),
        migrations.AddField(
            model_name='follow',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='type',
            field=models.CharField(default='follow', editable=False, max_length=15),
        ),
        migrations.AddField(
            model_name='follower',
            name='type',
            field=models.CharField(default='follower', editable=False, max_length=15),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='post', editable=False, max_length=15),
        ),
    ]
