# Generated by Django 5.0.2 on 2024-03-14 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetworking', '0005_remove_like_context_comment_url_like_object'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='commentInbox',
            field=models.ManyToManyField(to='socialNetworking.comment'),
        ),
        migrations.AddField(
            model_name='author',
            name='followInbox',
            field=models.ManyToManyField(to='socialNetworking.follow'),
        ),
        migrations.AddField(
            model_name='author',
            name='likeInbox',
            field=models.ManyToManyField(to='socialNetworking.like'),
        ),
        migrations.AddField(
            model_name='author',
            name='postInbox',
            field=models.ManyToManyField(to='socialNetworking.post'),
        ),
        migrations.AddField(
            model_name='like',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
