# Generated by Django 5.0.2 on 2024-02-21 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetworking', '0005_comment_type_follow_summary_follow_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.URLField(default='https://www.w3.org/ns/activitystreams', editable=False)),
                ('type', models.CharField(default='like', editable=False, max_length=15)),
                ('summary', models.TextField(blank=True)),
                ('author_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialNetworking.author')),
                ('like_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialNetworking.comment')),
                ('like_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialNetworking.post')),
            ],
        ),
    ]
