# Generated by Django 5.0.2 on 2024-02-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetworking', '0005_alter_post_options_post_shared_body_post_shared_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='lastCommitFetch',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
