# Generated by Django 4.2.10 on 2024-02-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetworking', '0007_alter_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
