# Generated by Django 5.0.2 on 2024-02-29 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('socialNetworking', '0008_follow_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='items_content_type',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='items_object_id',
        ),
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='inbox item', editable=False, max_length=15)),
                ('items_object_id', models.UUIDField()),
                ('items_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='inbox',
            name='item',
            field=models.ManyToManyField(to='socialNetworking.inboxitem'),
        ),
    ]
