# Generated by Django 5.0.2 on 2024-02-22 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('socialNetworking', '0008_alter_post_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='inbox', editable=False, max_length=15)),
                ('items_object_id', models.UUIDField()),
                ('inbox_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialNetworking.author')),
                ('items_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
