# Generated by Django 5.0.2 on 2024-02-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetworking', '0009_remove_inbox_items_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='item',
            field=models.ManyToManyField(related_name='inbox', to='socialNetworking.inboxitem'),
        ),
    ]
