# Generated by Django 5.0.2 on 2024-02-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetworking', '0010_alter_inbox_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='inbox', to='socialNetworking.inboxitem'),
        ),
    ]
