# Generated by Django 5.0.2 on 2024-02-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetworking', '0011_alter_inbox_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='item',
        ),
        migrations.AddField(
            model_name='inboxitem',
            name='inbox',
            field=models.ManyToManyField(related_name='items', to='socialNetworking.inbox'),
        ),
    ]
